version: "3"
services:
  web_scraper:
    build: ./web_scraper
    container_name: web_scraper  
    volumes:
      - shared-volume:/src
  web:
    build: ./web
    container_name: web
    ports:
      - "8888:5000"
    volumes:
      - shared-volume:/src
    depends_on:
      - web_scraper

volumes:
  shared-volume: